url: https://localflavor.github.io
baseurl: ""

# Site settings
company_name: Local Flavor Marketing Group, LLC
title: Design with Intention
email: localflavormktg@gmail.com
description: "Local Flavor Marketing Group is a small shop that helps you to tell the world your story and to give a voice to your authentic self."
logo: /img/lf_logo.png
medallion: /img/lf_medallion.png

collections:
  projects:
    output: true
  testimonials:
    output: true
  services:
    output: true

# Team names, titles and social links
people:
- name: Anne Richardson
  pic: anne
  position: Software Engineer, Graphic Designer
  social:
    - icon: fab fa-github
      url: https://github.com/lortza
    - icon: fab fa-stack-overflow
      url: https://stackoverflow.com/users/5009528/richardson?tab=profile
    - icon: fab fa-linkedin-in
      url: https://www.linkedin.com/in/richardsonae/
    - icon: fal fa-link
      url:  https://lortza.github.io

- name: Mike Vallano
  pic: mike
  position: Software Engineer, SEO/SEM
  social:
    - icon: fab fa-github
      url: https://github.com/mikevallano
    - icon: fab fa-twitter
      url: https://twitter.com/mikevallano?lang=en
    - icon: fab fa-linkedin-in
      url: https://www.linkedin.com/in/mikevallano
    - icon: fal fa-link
      url:  http://mikevallano.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 650 S. Cherry Street, Suite 1050
  - line: Glendale, CO 80246

# Build settings
markdown: kramdown
permalink: pretty
